### ISSUE TITLE
V3 PHSH Unknown Field Mismatch in Heroes of the Storm 2.48

### ISSUE THREAD

**Issue by neptuwunium** [Talv/m3addon#13]
`Expected that PHSHV3.unknown66ce545e has always the value b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', but it was b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x59\x01\x00\x00'`

```
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x59\x01\x00\x00
```

Model: `mods\heroes.stormmod\base.stormassets\Assets\Units\Heroes\Storm_Hero_Alexstrasza_Cowl\Storm_Hero_Alexstrasza_Cowl.m3` (PTR)

**Comment by Talv** [comment]
Fixed in 7a6285fdf96b23732fcde263e7f901b8655b937e
