### ISSUE TITLE
Wrecked SiegeTank

### ISSUE THREAD

**Issue by SheeldWall** [Talv/m3addon#2]
SiegeTankEx2_Wrecked model das not import correctly.
![332](https://user-images.githubusercontent.com/24306412/45587983-898f0400-b8db-11e8-997a-f3d227dcb2d0.PNG)

**Comment by Talv** [comment]
Fixed. But I didn't verify if everything was imported correctly. Let me know if there are any issues.

**Comment by SheeldWall** [comment]
ok
