### ISSUE TITLE
Mesh deformation with m3a animation applied

### ISSUE THREAD

**Issue by tonkado** [Talv/m3addon#22]
Here is a reference marine animation from StarCraft 2 multiplayer screen:
![2020-04-19_04-55-01](https://user-images.githubusercontent.com/13105418/79679063-6edce980-81fa-11ea-9fdf-b937fe488f55.png)

but when I import sm_marine03.m3 model and apply anims from UI_Screens_Multiplayer_Anims_Marine.m3a it renders differently:
![2020-04-19_04-55-55](https://user-images.githubusercontent.com/13105418/79679076-a055b500-81fa-11ea-8b85-681d3c406b94.png)

@Talv , could you please look and find the reason of that deform?
Could it be fixed?

Thanks in advance!

**Comment by Naznarok** [comment]
**Reference in editor:**
![Reference in editor](https://i.imgur.com/Oer8qbw.png)
**In blender with skeleton:**
![In blender with skeleton](https://i.imgur.com/wpMynEn.png)
**in blender without skeleton:**
![Without skeleton](https://i.imgur.com/YXJd0up.png)

Blender: 3.4.1
M3 Addon: Latest 0.5.1
Model: Assets\Units\Zerg\Zergling\Zergling.m3

Can confirm this error with another model.
