### ISSUE TITLE
Exporting Issue

### ISSUE THREAD

**Issue by bhain7** [Talv/m3addon#25]
I'm trying to export a basic cube to make sure the plugin works and can't export the basic cube.
Tried blender version 2.8 2.83 for good measure. No luck with either.
Help greatly appreciated! Excited to get into SC2 modding.

![image](https://user-images.githubusercontent.com/5784142/87104182-baf96200-c21c-11ea-813e-a0981b2246d1.png)

![image](https://user-images.githubusercontent.com/5784142/87104282-1166a080-c21d-11ea-9474-e4c2284cb6c9.png)

**Comment by Solstice245** [comment]
You need to delete the collection that is created in the startup scene. As
of right now, when exporting to m3 everything must be in the root directory
of your scene.

**Comment by DerekX** [comment]
It works. :) I was having that same issue, and now it's solved. :)
