### ISSUE TITLE
Void thrasher's

### ISSUE THREAD

**Issue by SheeldWall** [Talv/m3addon#3]
The Void_Thrasher, Void_Thrasher_Walker, and the VoidThrasherEx2_portrait models are nit importing correctly.
![333](https://user-images.githubusercontent.com/24306412/45598379-0b992e80-b9a9-11e8-99af-26a564f97995.PNG)
![334](https://user-images.githubusercontent.com/24306412/45598384-253a7600-b9a9-11e8-9ee5-c6aefa688ef8.PNG)
![335](https://user-images.githubusercontent.com/24306412/45598389-4307db00-b9a9-11e8-96b5-688f64d087ab.PNG)

**Comment by Talv** [comment]
Fixed import errors.
But these models have quite a lot of fancy stuff that isn't yet properly supported. I'll see what I can do about it in upcoming days.

**Comment by SheeldWall** [comment]
Do your best and tack your time.

**Comment by SheeldWall** [comment]
the void thrasher's do work in blender for now.

**Comment by SheeldWall** [comment]
it was fix with the colossus
