### ISSUE TITLE
Export Error on 2.92.0

### ISSUE THREAD

**Issue by NoisyMonk** [Talv/m3addon#30]
Any ideas what the problem might be? Just exporting a simple cube as a test.

![image](https://user-images.githubusercontent.com/25105923/110719883-a6220380-81db-11eb-9917-58c414483e92.png)

**Comment by Solstice245** [comment]
Delete the collection which the object is in and it should export fine.
Ideally I think it should, but hasn’t been dealt with yet.

**Comment by Solstice245** [comment]
I am now closing this issue as I believe this issue has been fixed.

**Comment by Solstice245** [comment]
I believe this has been fixed now, so I'm went ahead and closed this issue. If it somehow persists, just reopen the issue.
