### ISSUE TITLE
Upgrade to 2.8x required

### ISSUE THREAD

**Issue by aiodeus** [Talv/m3addon#31]
Does this addon support 2.83 LTS? Currently working using that program.

**Comment by Solstice245** [comment]
Have you tried it? I’ve been using this addon in 2.8x and 2.9x just fine.
You should at least test it yourself before submitting a question like this
as an issue.

**Comment by aiodeus** [comment]
Yes, I did. Sorry if I wasn't clear enough. The "Upgrade to 2.8x required" appeared on my screen and I haven't been able to export or import .m3 files on 2.83 LTS.

**Comment by Solstice245** [comment]
Ah, well then it's understandable. Unfortunately I don't have that version of blender installed and my internet availability is low at this time so I won't be downloading it to test it myself. Hopefully someone can help you.

**Comment by Solstice245** [comment]
I'll just additionally comment that if possible you should just install another version of Blender. (I use 2.92 atm and have no such problem) I don't see why you would need to stick to a LTS version unless this is somehow a part of a major production pipeline.
