### ISSUE TITLE
import / export (don't appear the option m3)

### ISSUE THREAD

**Issue by Terran99** [Talv/m3addon#36]
hello There, im triying to open a sc2 file m3 but don't have the option, the plugin has ben installed but dont give te option to import or export. im use the last version of blender 2.93
![001](https://user-images.githubusercontent.com/87795497/126590452-e5a7f569-2130-40d2-9bc0-6e7c988c7bac.png)
![002](https://user-images.githubusercontent.com/87795497/126590455-5c7b756b-7389-4002-bad4-a84af6355ad4.png)

**Comment by Talv** [comment]
That would indicate there's some sort of initialization error. I can't think of anything. The last version of Blender I've used this plugin on was `2.92`.

For now, I'd suggest launching Blender from command line in debug mode as per the guide: https://docs.blender.org/manual/en/latest/advanced/command_line/launch/windows.html (using `blender --debug`). And inspect the output - whether it displays any sort of error that could relate to m3addon. If there's something, please paste it here.

**Comment by Terran99** [comment]
Thanks you talv, i'm installing in manual mode and work it !! thanks you so much

**Comment by Solstice245** [comment]
If I understand right, the problem described in this issue has been resolved?
Closing for now, but if I'm missing something, feel free to request it to be opened again.
