### ISSUE TITLE
Error when trying to activate plugin on version 2.79

### ISSUE THREAD

**Issue by DerekX** [Talv/m3addon#40]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-2.79.0-git.e045fe53f1b0-windows64\2.79\scripts\modules\addon_utils.py", line 370, in enable
    mod.register()
  File "C:\Users\Derek Hendrickson\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\m3addon-master\__init__.py", line 6791, in register
    bpy.types.TOPBAR_MT_file_import.append(menu_func_import)
AttributeError: 'RNA_Types' object has no attribute 'TOPBAR_MT_file_import'

**Comment by Solstice245** [comment]
Which version of the addon did you download? Newer versions of the addon support only Blender 2.80+

**Comment by DerekX** [comment]
Actually, I just solved the issue. Downloaded the last version before being forked. [https://github.com/flo/m3addon](url)

**Comment by Solstice245** [comment]
Dang, really that against changing your Blender version? The latest version of the addon has MANY advantages over the older version.

**Comment by DerekX** [comment]
I actually have two different versions of Blender installed, the latest and a "classic" 2.79. I'm still trying to get used to the new (2.80) interface and controls.

**Comment by Solstice245** [comment]
Gotcha.
