### ISSUE TITLE
[BUG?] m3 model exported has got wrong texture path

### ISSUE THREAD

**Issue by TomcatSong** [Talv/m3addon#42]
I can't sure this is a bug. My export model from blender 2.93 can't link the right texture path. So, texture i made didn't appear.

here s the detail:

2022.02.07 I download m3addon-master addon. My Blender version is 2.93.
As a test, i import an official .m3 model to Blender, which exported from Starcraft2 editor.
In blender I change the texture path with new .dds file, and export with V23 (m3 version) . However, when I open the new exported m3 model file with notepad, the texture path string is still the old one, which cause the texture is not changed. The geometry works fine.

Is this a bug? or just somewhere i messed ?
[Voyager_Cube_01.zip](https://github.com/SC2Mapster/m3addon/files/8014531/Voyager_Cube_01.zip)

**Comment by Solstice245** [comment]
Assuming that you intended to set the texture path in your m3 model's material to Voyager_Cube_01.dds, it appears you were trying to do this inside of Blender's shader nodes, which is not the correct domain for editing M3 Material related properties.

To edit M3 Material properties properly, you should navigate to the Scene properties tab, then the M3 Materials panel, and the Layers -> Color subpanels, and then finally, edit the Image Path property to match the path string to the path of the texture relative to the map or mod's archive. (Conventionally, Assets/Textures/the_name_of_your_texture.dds)
