### ISSUE TITLE
Material Layers UI dies on imported models

### ISSUE THREAD

**Issue by DeffOS** [Talv/m3addon#44]
Tested on 3.2 and 2.83, every imported model doesnt expand layer properties. With no errors in console.
![image](https://user-images.githubusercontent.com/68462654/184322183-296aa4e4-a890-4274-9299-0baa0c707f21.png)
![image](https://user-images.githubusercontent.com/68462654/184322916-d570ad31-8f50-44c2-959b-0c51d6b5ad1e.png)

**Comment by DeffOS** [comment]
This only happens in Blender's Material Tab, if M3 Material selected in Scene tab it "fixes" in Material Tab, essentially revealing that M3 Material Selection does not select m3 material for editing.

**Comment by Solstice245** [comment]
Can confirm this is an issue, I'll look into a solution when I can (possibly tonight)
