### ISSUE TITLE
Clear information for next import

### ISSUE THREAD

**Issue by MajorCooke** [Talv/m3addon#45]
While using this addon I've noticed there's a few issues with importing. My plan was to set up different view layers for different monsters, and different scenes for each species with whom things belonged to.

However, when trying to import a marine, and then the tauren space marine after that, the animation data and more are not cleared which can lead to issues preventing further imports. I have to go through and manually clear everything out - including the M3 Import tab, and the M3 Animations tab. This means a lot more work on my end to get all the units in the game imported.

**Comment by Solstice245** [comment]
Due to the way the addon's architecture is set up, you must create a new scene, and not a new view layer when you want separate m3 models in one blend file.

**Comment by MajorCooke** [comment]
Turns out even with creating a new scene, including selecting "New" instead of "Copy Settings", still seems to bug out the importer no matter what. You have to make a whole new blend file instead. Because all the imported animation data will be blank as well - it won't give any frames whatsoever.

Great...

**Comment by Solstice245** [comment]
Yeah, that is what has always been done to my knowledge. Creating a new scene in the same Blend file I should think would work at least theoretically though.

**Comment by MajorCooke** [comment]
It doesn't. I have to make a whole new blend file instead.
