### ISSUE TITLE
Import failure

### ISSUE THREAD

**Issue by DeffOS** [Talv/m3addon#47]
Model used buildings/terran/refinery_hornerhan_coop.m3
Occurring on both 3.6 and 4.0 Blender versions
![image](https://github.com/SC2Mapster/m3addon/assets/68462654/d15cd349-d6b0-40a0-804c-70a49fd2da5c)

**Comment by CrazyBro** [comment]
I had the same problem, I tried importing a marine and got a similar error message with this result:
![image_2024-02-09_185603914](https://github.com/SC2Mapster/m3addon/assets/109482869/51fd89aa-a796-4b6f-aeb4-5fafbbf0fe8d)
